name: Lint

on:
  push:
    branches: [ "**" ]           # run on every branch (including main)
    paths:
      - "app/**"
      - "components/**"
      - "lib/**"
      - ".eslintrc.js"
      - "package.json"
      - "tsconfig.json"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.19.4
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.4"
          cache: "npm"

      - name: Install deps (CI)
        run: npm ci

      - name: Run ESLint (fail on warnings)
        run: npx eslint "app/**/*.{ts,tsx,js,jsx}" --max-warnings=0
