name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.19.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.1'
          cache: 'npm'

      - name: Install deps (ci with fallback)
        run: |
    if npm ci; then
      echo "npm ci OK"
    else
      echo "npm ci failed; trying npm install with legacy peers"
      npm install --legacy-peer-deps
    fi

      - name: Run ESLint
        run: npm run lint
